name: Deploy to Production Server

on:
  push:
    branches: [master]
  workflow_dispatch:

concurrency:
  group: deploy-blockstr
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: [self-hosted, blockstr]
    timeout-minutes: 10
    steps:
      - name: Run deploy script
        run: /home/ubuntu/gamestr/deploy blockstr
